# .github/workflows/pr-checks.yml
name: PR Checks
on:
  pull_request:
    branches: [ main, develop ]
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - run: npx prettier --check .
      - run: npx tsc --noEmit
      - run: npx eslint . --max-warnings=0
      - run: npx vitest --run --reporter=dot

  k8s:
    if: contains(github.event.pull_request.changed_files, 'k8s/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/yannh/kubeconform:latest
        with: { args: "-strict -summary k8s" }
      - uses: stackrox/kube-linter-action@v1
        with: { directory: "k8s" }
